"""
BMS symbolic map generator — produces COBOL copybook source from BMS map
definitions, replacing the IBM DFHCSDUP assembler utility.

For each BMS map XXXX, generates two 01-level records:
- XXXXI (input map): fields with L (length), F (flag), A (attribute), I (data) suffixes
- XXXXO (output map): fields with L, F, A, O (data) suffixes

This allows CICS programs that COPY the symbolic map to compile with GnuCOBOL
without a CICS preprocessor.

IBM BMS symbolic map field layout per named field:
  05 <name>L    PIC S9(4) COMP.     (input length)
  05 <name>F    PIC X.               (flag byte)
  05 FILLER     PIC X(0002).         (unused)
  05 <name>A    PIC X.               (attribute byte) — in output map only reused
  05 <name>I    PIC X(<length>).     (input data)
  -- or --
  05 <name>O    REDEFINES <name>I PIC X(<length>). (output data, redefines input)
"""

import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

from bms_parser import BmsMap, BmsMapset, BmsField, parse_bms_file


def generate_symbolic_map(bms_map: BmsMap) -> str:
    """Generate COBOL symbolic map copybook for a BMS map.

    Produces both the input (I) and output (O) 01-level records in a single
    copybook, matching the IBM DFHCSDUP output format.
    """
    map_name = bms_map.name  # e.g., COSGN0A
    lines = []

    lines.append(f"      * Generated symbolic map for {map_name}")
    lines.append(f"      * Mapset: {bms_map.mapset}")
    lines.append(f"      * Generated by Masquerade BMS Symbolic Map Generator")
    lines.append(f"      *")

    # ── Input map (XXXXI) ──
    lines.append(f"       01  {map_name}I.")
    lines.append(f"           02  FILLER                    PIC X(12).")

    for f in bms_map.fields:
        if not f.name:
            continue
        name = f.name
        length = max(f.length, 1)

        lines.append(f"           02  {name}L")
        lines.append(f"               PIC S9(4) COMP.")
        lines.append(f"           02  {name}F")
        lines.append(f"               PIC X.")
        lines.append(f"           02  FILLER")
        lines.append(f"               PIC X(2).")
        lines.append(f"           02  {name}I")
        lines.append(f"               PIC X({length:02d}).")

    lines.append(f"      *")

    # ── Output map (XXXXO) ──
    lines.append(f"       01  {map_name}O REDEFINES {map_name}I.")
    lines.append(f"           02  FILLER                    PIC X(12).")

    for f in bms_map.fields:
        if not f.name:
            continue
        name = f.name
        length = max(f.length, 1)

        lines.append(f"           02  FILLER")
        lines.append(f"               PIC X(3).")
        lines.append(f"           02  {name}A")
        lines.append(f"               PIC X.")
        lines.append(f"           02  {name}O")
        lines.append(f"               PIC X({length:02d}).")

    lines.append(f"      *")
    lines.append(f"")

    return "\n".join(lines)


def generate_symbolic_maps_for_mapset(mapset: BmsMapset) -> dict[str, str]:
    """Generate symbolic map copybooks for all maps in a mapset.

    Returns a dict of copybook_name → COBOL source.
    For mapset COSGN00 with map COSGN0A, produces {"COSGN00": "<source>"}.
    """
    parts = []
    for bms_map in mapset.maps:
        parts.append(generate_symbolic_map(bms_map))

    return {mapset.name: "\n".join(parts)}


def generate_all_symbolic_maps(
    bms_dir: str,
    output_dir: str,
) -> list[str]:
    """Generate symbolic map copybooks for all BMS files in a directory.

    Writes .cpy files to output_dir. Returns list of generated file paths.
    """
    generated = []
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    for bms_file in Path(bms_dir).glob("*.bms"):
        mapset = parse_bms_file(bms_file)
        if not mapset:
            continue

        maps = generate_symbolic_maps_for_mapset(mapset)
        for name, source in maps.items():
            cpy_path = out_path / f"{name}.cpy"
            cpy_path.write_text(source, encoding="utf-8")
            generated.append(str(cpy_path))

    return generated
