"""
Reimplementation of COBOL program DBCRFUN — Debit/Credit Function.

Original: cbsa/src/base/cobol_src/DBCRFUN.cbl
Business: Takes an account number and amount, reads the account from DB2,
          applies the debit or credit, updates the account, and writes a
          processed transaction record.

Copybook layouts:
  PAYDBCR.cpy — COMMAREA (request/response)
  ACCOUNT.cpy — Account record
  PROCTRAN.cpy — Processed transaction record
  SORTCODE.cpy — Bank sort code constant (987654)

Generated by Masquerade COBOL Intelligence Engine.
"""

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Optional


# -- Constants (from SORTCODE.cpy) --------------------------------------------

SORTCODE = "987654"

# COMM-FACILTYPE value indicating a PAYMENT (as opposed to a teller operation).
# In the COBOL: COMM-FACILTYPE = 496 means FACILITY-TYPE = NONE, i.e. no
# terminal attached, which identifies a programmatic payment request.
FACILTYPE_PAYMENT = 496

# Account types that cannot be debited or credited via PAYMENT
RESTRICTED_ACCOUNT_TYPES = ("MORTGAGE", "LOAN")


# -- Data Structures (from copybooks) ----------------------------------------

@dataclass
class Account:
    """From ACCOUNT.cpy -- account record in the ACCOUNT DB2 datastore.

    PIC layouts:
      ACCOUNT-EYE-CATCHER        PIC X(4)
      ACCOUNT-CUST-NO            PIC 9(10)
      ACCOUNT-SORT-CODE          PIC 9(6)
      ACCOUNT-NUMBER             PIC 9(8)
      ACCOUNT-TYPE               PIC X(8)
      ACCOUNT-INTEREST-RATE      PIC 9(4)V99
      ACCOUNT-OPENED             PIC 9(8)
      ACCOUNT-OVERDRAFT-LIMIT    PIC 9(8)
      ACCOUNT-LAST-STMT-DATE     PIC 9(8)
      ACCOUNT-NEXT-STMT-DATE     PIC 9(8)
      ACCOUNT-AVAILABLE-BALANCE  PIC S9(10)V99
      ACCOUNT-ACTUAL-BALANCE     PIC S9(10)V99
    """
    eyecatcher: str = "ACCT"
    cust_no: str = "0000000000"
    sortcode: str = "000000"
    acc_no: str = "00000000"
    acc_type: str = ""
    int_rate: Decimal = Decimal("0.00")
    opened: str = "00000000"
    overdraft_lim: int = 0
    last_stmt: str = "00000000"
    next_stmt: str = "00000000"
    avail_bal: Decimal = Decimal("0.00")
    actual_bal: Decimal = Decimal("0.00")


@dataclass
class DebitCreditRequest:
    """From PAYDBCR.cpy -- the COMMAREA input fields.

    PIC layouts:
      COMM-ACCNO       PIC X(8)
      COMM-AMT         PIC S9(10)V99
      COMM-SORTC       PIC 9(6)       (output -- set by program)
      COMM-ORIGIN      group containing COMM-FACILTYPE S9(8) COMP
    """
    sortcode: str = SORTCODE
    acc_no: str = ""
    amount: Decimal = Decimal("0.00")
    facil_type: int = 0
    origin: str = ""


@dataclass
class DebitCreditResult:
    """From PAYDBCR.cpy -- the COMMAREA output fields.

    PIC layouts:
      COMM-AV-BAL      PIC S9(10)V99
      COMM-ACT-BAL     PIC S9(10)V99
      COMM-SUCCESS     PIC X
      COMM-FAIL-CODE   PIC X
    """
    success: bool = False
    fail_code: str = "0"
    avail_bal: Decimal = Decimal("0.00")
    actual_bal: Decimal = Decimal("0.00")
    sortcode: str = SORTCODE


@dataclass
class ProcTranRecord:
    """From PROCTRAN.cpy -- processed transaction record written to DB2.

    Key fields:
      PROC-TRAN-EYE-CATCHER  PIC X(4)   = 'PRTR'
      PROC-TRAN-SORT-CODE    PIC 9(6)
      PROC-TRAN-NUMBER       PIC 9(8)
      PROC-TRAN-DATE         PIC X(10)
      PROC-TRAN-TIME         PIC X(6)
      PROC-TRAN-REF          PIC X(12)
      PROC-TRAN-TYPE         PIC X(3)   DEB/CRE/PDR/PCR
      PROC-TRAN-DESC         PIC X(40)
      PROC-TRAN-AMOUNT       PIC S9(10)V99
    """
    eyecatcher: str = "PRTR"
    sortcode: str = ""
    acc_no: str = ""
    date: str = ""
    time: str = ""
    ref: str = ""
    tran_type: str = ""
    desc: str = ""
    amount: Decimal = Decimal("0.00")


# -- Repository Interfaces ----------------------------------------------------

class AccountRepository:
    """Abstract repository for the ACCOUNT DB2 datastore.

    Maps to the SQL SELECT/UPDATE operations in DBCRFUN.cbl
    (UPDATE-ACCOUNT-DB2 section).
    """

    def find(self, sortcode: str, acc_no: str) -> Optional[Account]:
        """Read account by sortcode + account number.

        Returns Account if found, None if not found.
        Raises RuntimeError for SQL errors other than not-found.
        """
        raise NotImplementedError

    def update(self, account: Account) -> bool:
        """Update account record in DB2.

        Returns True on success, False on SQL error.
        """
        raise NotImplementedError


class ProcTranRepository:
    """Abstract repository for the PROCTRAN DB2 datastore.

    Maps to the INSERT in WRITE-TO-PROCTRAN-DB2 section.
    """

    def insert(self, record: ProcTranRecord) -> bool:
        """Insert a processed transaction record.

        Returns True on success, False on SQL error.
        """
        raise NotImplementedError


# -- In-Memory Repository Implementations (for testing) -----------------------

class InMemoryAccountRepository(AccountRepository):
    """In-memory account store for unit testing."""

    def __init__(self, accounts: Optional[dict[str, Account]] = None):
        self._accounts: dict[str, Account] = accounts or {}

    def _key(self, sortcode: str, acc_no: str) -> str:
        return f"{sortcode}:{acc_no}"

    def add(self, account: Account) -> None:
        self._accounts[self._key(account.sortcode, account.acc_no)] = account

    def find(self, sortcode: str, acc_no: str) -> Optional[Account]:
        return self._accounts.get(self._key(sortcode, acc_no))

    def update(self, account: Account) -> bool:
        key = self._key(account.sortcode, account.acc_no)
        if key in self._accounts:
            self._accounts[key] = account
            return True
        return False


class InMemoryProcTranRepository(ProcTranRepository):
    """In-memory processed transaction store for unit testing."""

    def __init__(self):
        self.records: list[ProcTranRecord] = []

    def insert(self, record: ProcTranRecord) -> bool:
        self.records.append(record)
        return True


class FailingProcTranRepository(ProcTranRepository):
    """Repository that always fails on insert (simulates SQL error)."""

    def insert(self, record: ProcTranRecord) -> bool:
        return False


# -- Business Logic -----------------------------------------------------------


def _is_restricted_account_type(acc_type: str) -> bool:
    """Check if the account type is MORTGAGE or LOAN.

    COBOL uses PIC X(8) so 'LOAN' is stored as 'LOAN    ' (padded).
    We strip for comparison.  The COBOL does:
        IF HV-ACCOUNT-ACC-TYPE = 'MORTGAGE'
        IF HV-ACCOUNT-ACC-TYPE = 'LOAN    '
    """
    return acc_type.strip().upper() in RESTRICTED_ACCOUNT_TYPES


def _classify_transaction(amount: Decimal, facil_type: int) -> tuple[str, str]:
    """Determine transaction type code and default description.

    From WRITE-TO-PROCTRAN-DB2 section (lines 491-517):

      IF COMM-AMT < 0                         (debit)
         MOVE 'DEB' TO HV-PROCTRAN-TYPE
         MOVE 'COUNTER WTHDRW' TO HV-PROCTRAN-DESC
         IF COMM-FACILTYPE = 496              (payment)
            MOVE 'PDR' TO HV-PROCTRAN-TYPE
            MOVE COMM-ORIGIN(1:14) TO HV-PROCTRAN-DESC
      ELSE                                    (credit)
         MOVE 'CRE' TO HV-PROCTRAN-TYPE
         MOVE 'COUNTER RECVED' TO HV-PROCTRAN-DESC
         IF COMM-FACILTYPE = 496              (payment)
            MOVE 'PCR' TO HV-PROCTRAN-TYPE
            MOVE COMM-ORIGIN(1:14) TO HV-PROCTRAN-DESC

    Returns (tran_type, default_desc).  For payment types the caller
    must override desc with origin[:14].
    """
    if amount < 0:
        if facil_type == FACILTYPE_PAYMENT:
            return "PDR", ""
        return "DEB", "COUNTER WTHDRW"
    else:
        if facil_type == FACILTYPE_PAYMENT:
            return "PCR", ""
        return "CRE", "COUNTER RECVED"


def process_debit_credit(
    request: DebitCreditRequest,
    account_repo: AccountRepository,
    proctran_repo: ProcTranRepository,
) -> DebitCreditResult:
    """Process a debit or credit transaction.

    This is the reimplementation of DBCRFUN's PROCEDURE DIVISION.
    The COBOL flow in UPDATE-ACCOUNT-DB2 section:

    1. Initialize: COMM-SUCCESS = 'N', COMM-FAIL-CODE = '0'
    2. Set COMM-SORTC from SORTCODE constant (987654)
    3. SELECT account by sortcode + acc_no
       - SQLCODE = +100 (not found)  -> fail_code '1'
       - SQLCODE != 0 (other error)  -> fail_code '2'
    4. IF COMM-AMT < 0  (debit / payment):
       a. IF acc_type is MORTGAGE or LOAN AND FACILTYPE=496
             -> fail_code '4'  (cannot debit restricted account via payment)
       b. IF avail_bal + amount < 0 AND FACILTYPE=496
             -> fail_code '3'  (insufficient funds for payment)
    5. After the debit IF block, a SECOND check (lines 368-376):
       IF acc_type is MORTGAGE or LOAN AND FACILTYPE=496
          -> fail_code '4'  (catches credits to restricted accounts via payment)
    6. Compute new balances: avail += amount, actual += amount
    7. UPDATE account in DB2
       - SQLCODE != 0 -> fail_code '2'
    8. WRITE-TO-PROCTRAN
       - INSERT fails  -> ROLLBACK account, fail_code '2'
       - INSERT succeeds -> COMM-SUCCESS='Y', COMM-FAIL-CODE='0'
    9. Return updated balances in COMMAREA
    """
    result = DebitCreditResult()
    result.sortcode = SORTCODE

    # Step 3: Read the account record
    account = account_repo.find(SORTCODE, request.acc_no)

    if account is None:
        # SQLCODE = +100 -> account not found
        result.success = False
        result.fail_code = "1"
        return result

    # Step 4: Debit-specific checks (COMM-AMT < 0)
    if request.amount < 0:
        # 4a: Restricted account type check for PAYMENT
        if _is_restricted_account_type(account.acc_type) and \
           request.facil_type == FACILTYPE_PAYMENT:
            result.success = False
            result.fail_code = "4"
            return result

        # 4b: Insufficient funds check for PAYMENT
        difference = account.avail_bal + request.amount
        if difference < 0 and request.facil_type == FACILTYPE_PAYMENT:
            result.success = False
            result.fail_code = "3"
            return result

    # Step 5: Credit check for restricted account types via PAYMENT
    # This is the second IF block in the COBOL (lines 368-376), OUTSIDE
    # the "IF COMM-AMT < 0" block.  It catches the case where a credit
    # is attempted on a MORTGAGE or LOAN account via PAYMENT.
    if _is_restricted_account_type(account.acc_type) and \
       request.facil_type == FACILTYPE_PAYMENT:
        result.success = False
        result.fail_code = "4"
        return result

    # Step 6: Compute new balances
    account.avail_bal = account.avail_bal + request.amount
    account.actual_bal = account.actual_bal + request.amount

    # Step 7: Update account in DB2
    update_ok = account_repo.update(account)

    # The COBOL moves the new balances to COMMAREA before checking SQLCODE
    result.avail_bal = account.avail_bal
    result.actual_bal = account.actual_bal

    if not update_ok:
        result.success = False
        result.fail_code = "2"
        return result

    # Step 8: Write PROCTRAN record
    tran_type, desc = _classify_transaction(request.amount, request.facil_type)

    # For PAYMENT types (PDR/PCR), description is COMM-ORIGIN(1:14)
    if request.facil_type == FACILTYPE_PAYMENT:
        desc = (request.origin or "")[:14]

    now = datetime.now()

    proctran = ProcTranRecord(
        eyecatcher="PRTR",
        sortcode=SORTCODE,
        acc_no=request.acc_no,
        date=now.strftime("%d.%m.%Y"),
        time=now.strftime("%H%M%S"),
        ref="000000000000",
        tran_type=tran_type,
        desc=desc,
        amount=request.amount,
    )

    insert_ok = proctran_repo.insert(proctran)

    if not insert_ok:
        # COBOL does SYNCPOINT ROLLBACK -- revert the account balances
        account.avail_bal = account.avail_bal - request.amount
        account.actual_bal = account.actual_bal - request.amount
        account_repo.update(account)

        result.success = False
        result.fail_code = "2"
        return result

    # Step 9: Success
    result.success = True
    result.fail_code = "0"
    return result
