"""
Modern Python equivalent of COBOL program COPAUS1C.

Original: app/app-authorization-ims-db2-mq/cbl/COPAUS1C.cbl
Type: CICS Online
Lines: 461 code / 604 total
Complexity: 40 (grade: HIGH)
Readiness: 49.5/100
Effort estimate: 6.0 person-days

Generated by Masquerade COBOL Intelligence Engine.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import ClassVar, Optional, List
# Original CICS program — suggest REST/API framework
# from fastapi import APIRouter, HTTPException


@dataclass
class CdemoGeneralInfo:
    """Data structure from COBOL group CDEMO-GENERAL-INFO."""
    cdemo_from_tranid: str = field(default='', metadata={'pic': 'X(04)', 'max_length': 4})
    cdemo_from_program: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    cdemo_to_tranid: str = field(default='', metadata={'pic': 'X(04)', 'max_length': 4})
    cdemo_to_program: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    cdemo_user_id: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    CDEMO_USRTYP_ADMIN: ClassVar[str] = 'A'
    CDEMO_USRTYP_USER: ClassVar[str] = 'U'
    cdemo_user_type: str = field(default='', metadata={'pic': 'X(01)', 'max_length': 1})
    CDEMO_PGM_ENTER: ClassVar[str] = '0'
    CDEMO_PGM_REENTER: ClassVar[str] = '1'
    cdemo_pgm_context: int = field(default=0, metadata={'pic': '9(01)', 'max_digits': 1})


@dataclass
class CdemoCustomerInfo:
    """Data structure from COBOL group CDEMO-CUSTOMER-INFO."""
    cdemo_cust_id: int = field(default=0, metadata={'pic': '9(09)', 'max_digits': 9})
    cdemo_cust_fname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    cdemo_cust_mname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    cdemo_cust_lname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})


@dataclass
class CdemoAccountInfo:
    """Data structure from COBOL group CDEMO-ACCOUNT-INFO."""
    cdemo_acct_id: int = field(default=0, metadata={'pic': '9(11)', 'max_digits': 11})
    cdemo_acct_status: str = field(default='', metadata={'pic': 'X(01)', 'max_length': 1})


@dataclass
class CdemoCardInfo:
    """Data structure from COBOL group CDEMO-CARD-INFO."""
    cdemo_card_num: int = field(default=0, metadata={'pic': '9(16)', 'max_digits': 16})


@dataclass
class CdemoMoreInfo:
    """Data structure from COBOL group CDEMO-MORE-INFO."""
    cdemo_last_map: str = field(default='', metadata={'pic': 'X(7)', 'max_length': 7})
    cdemo_last_mapset: str = field(default='', metadata={'pic': 'X(7)', 'max_length': 7})


@dataclass
class CarddemoCommarea:
    """Data structure from COBOL copybook COCOM01Y."""
    cdemo_general_info: CdemoGeneralInfo = field(default_factory=CdemoGeneralInfo)
    cdemo_customer_info: CdemoCustomerInfo = field(default_factory=CdemoCustomerInfo)
    cdemo_account_info: CdemoAccountInfo = field(default_factory=CdemoAccountInfo)
    cdemo_card_info: CdemoCardInfo = field(default_factory=CdemoCardInfo)
    cdemo_more_info: CdemoMoreInfo = field(default_factory=CdemoMoreInfo)

Cocom01y = CarddemoCommarea


@dataclass
class Copau1ai:
    """Data structure from COBOL copybook COPAU01."""
    trnnamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnnamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamei: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    title01l: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    title01f: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01i: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curdatel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    curdatef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    pgmnamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    pgmnamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    title02l: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    title02f: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02i: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curtimel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    curtimef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    cardnuml: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    cardnumf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumi: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    authdtl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authdtf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authdti: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    authtml: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authtmf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtmi: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    authrspl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authrspf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrspi: str = field(default='', metadata={'pic': 'X(1)', 'max_length': 1})
    authrsnl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authrsnf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsni: str = field(default='', metadata={'pic': 'X(20)', 'max_length': 20})
    authcdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authcdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authcdi: str = field(default='', metadata={'pic': 'X(6)', 'max_length': 6})
    authamtl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authamtf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authamti: str = field(default='', metadata={'pic': 'X(12)', 'max_length': 12})
    posemdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    posemdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    posemdi: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    authsrcl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authsrcf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authsrci: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    mcccdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mcccdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcccdi: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    crdexpl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    crdexpf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    crdexpi: str = field(default='', metadata={'pic': 'X(5)', 'max_length': 5})
    authtypl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authtypf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtypi: str = field(default='', metadata={'pic': 'X(14)', 'max_length': 14})
    trnidl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnidf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidi: str = field(default='', metadata={'pic': 'X(15)', 'max_length': 15})
    authmtcl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authmtcf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authmtci: str = field(default='', metadata={'pic': 'X(1)', 'max_length': 1})
    authfrdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    authfrdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authfrdi: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    mernamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mernamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mernamei: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    meridl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    meridf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    meridi: str = field(default='', metadata={'pic': 'X(15)', 'max_length': 15})
    mercityl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mercityf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mercityi: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    merstl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    merstf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mersti: str = field(default='', metadata={'pic': 'X(2)', 'max_length': 2})
    merzipl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    merzipf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merzipi: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    errmsgl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    errmsgf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgi: str = field(default='', metadata={'pic': 'X(78)', 'max_length': 78})
    trnnamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnameo: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    title01c: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01p: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01h: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01v: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01o: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curdatec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdateh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdateo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    pgmnamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnameo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    title02c: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02p: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02h: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02v: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02o: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curtimec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimeh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimeo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    cardnumc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnump: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumo: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    authdtc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authdtp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authdth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authdtv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authdto: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    authtmc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtmp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtmh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtmv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtmo: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    authrspc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrspp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsph: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrspv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrspo: str = field(default='', metadata={'pic': 'X(1)', 'max_length': 1})
    authrsnc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsnp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsnh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsnv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authrsno: str = field(default='', metadata={'pic': 'X(20)', 'max_length': 20})
    authcdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authcdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authcdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authcdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authcdo: str = field(default='', metadata={'pic': 'X(6)', 'max_length': 6})
    authamtc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authamtp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authamth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authamtv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authamto: str = field(default='', metadata={'pic': 'X(12)', 'max_length': 12})
    posemdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    posemdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    posemdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    posemdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    posemdo: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    authsrcc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authsrcp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authsrch: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authsrcv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authsrco: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    mcccdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcccdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcccdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcccdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcccdo: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    crdexpc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    crdexpp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    crdexph: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    crdexpv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    crdexpo: str = field(default='', metadata={'pic': 'X(5)', 'max_length': 5})
    authtypc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtypp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtyph: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtypv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authtypo: str = field(default='', metadata={'pic': 'X(14)', 'max_length': 14})
    trnidc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnido: str = field(default='', metadata={'pic': 'X(15)', 'max_length': 15})
    authmtcc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authmtcp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authmtch: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authmtcv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authmtco: str = field(default='', metadata={'pic': 'X(1)', 'max_length': 1})
    authfrdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authfrdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authfrdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authfrdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    authfrdo: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    mernamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mernamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mernameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mernamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mernameo: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    meridc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    meridp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    meridh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    meridv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merido: str = field(default='', metadata={'pic': 'X(15)', 'max_length': 15})
    mercityc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mercityp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mercityh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mercityv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mercityo: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    merstc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merstp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mersth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merstv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mersto: str = field(default='', metadata={'pic': 'X(2)', 'max_length': 2})
    merzipc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merzipp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merziph: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merzipv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    merzipo: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    errmsgc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgo: str = field(default='', metadata={'pic': 'X(78)', 'max_length': 78})

Copau01 = Copau1ai


@dataclass
class CcdaScreenTitle:
    """Data structure from COBOL copybook COTTL01Y."""
    ccda_title01: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    ccda_title02: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    ccda_thank_you: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})

Cottl01y = CcdaScreenTitle


@dataclass
class WsCurdate:
    """Data structure from COBOL group WS-CURDATE."""
    ws_curdate_year: int = field(default=0, metadata={'pic': '9(04)', 'max_digits': 4})
    ws_curdate_month: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_day: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurtime:
    """Data structure from COBOL group WS-CURTIME."""
    ws_curtime_hours: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_minute: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_second: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_milsec: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurdateData:
    """Data structure from COBOL group WS-CURDATE-DATA."""
    ws_curdate: WsCurdate = field(default_factory=WsCurdate)
    ws_curdate_n: Optional[int] = field(default=None, metadata={'pic': '9(08)', 'max_digits': 8})  # REDEFINES WS-CURDATE
    ws_curtime: WsCurtime = field(default_factory=WsCurtime)
    ws_curtime_n: Optional[int] = field(default=None, metadata={'pic': '9(08)', 'max_digits': 8})  # REDEFINES WS-CURTIME


@dataclass
class WsCurdateMmDdYy:
    """Data structure from COBOL group WS-CURDATE-MM-DD-YY."""
    ws_curdate_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_dd: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_yy: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurtimeHhMmSs:
    """Data structure from COBOL group WS-CURTIME-HH-MM-SS."""
    ws_curtime_hh: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_ss: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsTimestamp:
    """Data structure from COBOL group WS-TIMESTAMP."""
    ws_timestamp_dt_yyyy: int = field(default=0, metadata={'pic': '9(04)', 'max_digits': 4})
    ws_timestamp_dt_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_dt_dd: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_hh: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_ss: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_ms6: int = field(default=0, metadata={'pic': '9(06)', 'max_digits': 6})


@dataclass
class WsDateTime:
    """Data structure from COBOL copybook CSDAT01Y."""
    ws_curdate_data: WsCurdateData = field(default_factory=WsCurdateData)
    ws_curdate_mm_dd_yy: WsCurdateMmDdYy = field(default_factory=WsCurdateMmDdYy)
    ws_curtime_hh_mm_ss: WsCurtimeHhMmSs = field(default_factory=WsCurtimeHhMmSs)
    ws_timestamp: WsTimestamp = field(default_factory=WsTimestamp)

Csdat01y = WsDateTime


@dataclass
class CcdaCommonMessages:
    """Data structure from COBOL copybook CSMSG01Y."""
    ccda_msg_thank_you: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})
    ccda_msg_invalid_key: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})

Csmsg01y = CcdaCommonMessages


@dataclass
class AbendData:
    """Data structure from COBOL copybook CSMSG02Y."""
    abend_code: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    abend_culprit: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    abend_reason: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})
    abend_msg: str = field(default='', metadata={'pic': 'X(72)', 'max_length': 72})

Csmsg02y = AbendData


@dataclass
class PaAcctId:
    """Data structure from COBOL copybook CIPAUSMY."""
    pass

Cipausmy = PaAcctId


@dataclass
class PaAuthorizationKey:
    """Data structure from COBOL copybook CIPAUDTY."""
    pa_auth_date_9c: int = field(default=0, metadata={'pic': 'S9(05)', 'max_digits': 5, 'signed': True, 'usage': 'COMP'})
    pa_auth_time_9c: int = field(default=0, metadata={'pic': 'S9(09)', 'max_digits': 9, 'signed': True, 'usage': 'COMP'})
    PA_AUTH_APPROVED: ClassVar[str] = '00'
    PA_MATCH_PENDING: ClassVar[str] = 'P'
    PA_MATCH_AUTH_DECLINED: ClassVar[str] = 'D'
    PA_MATCH_PENDING_EXPIRED: ClassVar[str] = 'E'
    PA_MATCHED_WITH_TRAN: ClassVar[str] = 'M'
    PA_FRAUD_CONFIRMED: ClassVar[str] = 'F'
    PA_FRAUD_REMOVED: ClassVar[str] = 'R'

Cipaudty = PaAuthorizationKey


@dataclass
class Dfhaid:
    """Data structure from COBOL copybook DFHAID.
    
    TODO: Map fields from copybook definition.
    """
    pass


@dataclass
class Dfhbmsca:
    """Data structure from COBOL copybook DFHBMSCA.
    
    TODO: Map fields from copybook definition.
    """
    pass


class Copaus1c:
    """
    Modern equivalent of COBOL program COPAUS1C.
    
    Calls: WS-PGM-AUTH-FRAUD, CDEMO-TO-PROGRAM
    Files: COPAU1A (CICS_IO), COPAU1A (CICS_IO), COPAU1A (CICS_IO)
    """

    def __init__(self):
        self.cocom01y = Cocom01y()
        self.copau01 = Copau01()
        self.cottl01y = Cottl01y()
        self.csdat01y = Csdat01y()
        self.csmsg01y = Csmsg01y()
        self.csmsg02y = Csmsg02y()
        self.cipausmy = Cipausmy()
        self.cipaudty = Cipaudty()
        self.dfhaid = Dfhaid()
        self.dfhbmsca = Dfhbmsca()

    def main_para(self) -> None:
        """
        COBOL PERFORMs: , , , , , 
        CICS: RETURN()
        Writes: CARDDEMO-COMMAREA, CCDA-MSG-INVALID-KEY, CDEMO-CPVD-FRAUD-DATA, CDEMO-PGM-REENTER, CDEMO-TO-PROGRAM
        """
        # CICS RETURN()

    def process_enter_key(self) -> None:
        """
        COBOL PERFORMs: , , 
        Writes: CDEMO-ACCT-ID, CDEMO-CPVD-PAU-SELECTED, COPAU1AO, ERR-FLG-ON, IMS-PSB-NOT-SCHD
        """

    def mark_auth_fraud(self) -> None:
        """
        COBOL PERFORMs: , , , 
        COBOL CALLs: 
        CICS: LINK()
        Writes: CDEMO-ACCT-ID, CDEMO-CPVD-PAU-SELECTED, CDEMO-CUST-ID, CICS, COMMAREA
        """
        # CICS LINK()
        # TODO: Replace with service call

    def process_pf8_key(self) -> None:
        """
        COBOL PERFORMs: , , , 
        Writes: ALREADY, AT, AUTHORIZATION, AUTHS-EOF, CDEMO-CPVD-PAU-SELECTED
        """

    def populate_auth_details(self) -> None:
        """
        Writes: ALL, AT, AUTHAMTO, AUTHCDO, AUTHDTO
        """
        raise NotImplementedError

    def return_to_prev_screen(self) -> None:
        """
        COBOL CALLs: 
        CICS: XCTL()
        Writes: CARDDEMO-COMMAREA, CDEMO-FROM-PROGRAM, CDEMO-FROM-TRANID, CDEMO-PGM-CONTEXT, CDEMO-PGM-ENTER
        """
        # CICS XCTL()
        # TODO: Replace with service call

    def send_authview_screen(self) -> None:
        """
        COBOL PERFORMs: 
        CICS: SEND(), SEND()
        Writes: CARDNUML, CICS, COPAU01, COPAU1A, COPAU1AO
        """
        # CICS SEND()
        # TODO: Replace with API endpoint handler
        # CICS SEND()
        # TODO: Replace with API endpoint handler

    def receive_authview_screen(self) -> None:
        """
        CICS: RECEIVE()
        """
        # CICS RECEIVE()
        # TODO: Replace with API endpoint handler

    def populate_header_info(self) -> None:
        """
        Writes: CCDA-TITLE01, CCDA-TITLE02, COPAU1AO, CURDATEO, CURTIMEO
        """
        raise NotImplementedError

    def read_auth_record(self) -> None:
        """
        COBOL PERFORMs: , 
        Writes: ACCNTID, AUTH, AUTHS-EOF, AUTHS-NOT-EOF, CODE
        """

    def read_next_auth_record(self) -> None:
        """
        COBOL PERFORMs: 
        Writes: AUTH, AUTHS-EOF, AUTHS-NOT-EOF, CODE, DELIMITED
        """

    def update_auth_details(self) -> None:
        """
        COBOL PERFORMs: , , 
        Writes: AUTH, DELIMITED, DIBSTAT, DLI, DT
        """

    def take_syncpoint(self) -> None:
        """
        CICS: SYNCPOINT()
        """
        # CICS SYNCPOINT()

    def roll_back(self) -> None:
        """
        CICS: SYNCPOINT()
        """
        # CICS SYNCPOINT()

    def schedule_psb(self) -> None:
        """
        COBOL PERFORMs: 
        Writes: CODE, DELIMITED, DIBSTAT, DLI, ERROR
        """

    def run(self) -> None:
        """Main entry point — mirrors PROCEDURE DIVISION."""
        self.main_para()
        self.process_enter_key()
        self.mark_auth_fraud()


if __name__ == "__main__":
    program = Copaus1c()
    program.run()
