"""
Modern Python equivalent of COBOL program COTRN01C.

Original: app/cbl/COTRN01C.cbl
Type: CICS Online
Lines: 231 code / 330 total
Complexity: 18 (grade: MODERATE)
Readiness: 59.5/100
Effort estimate: 2.0 person-days

Generated by Masquerade COBOL Intelligence Engine.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import ClassVar, Optional, List
# Original CICS program — suggest REST/API framework
# from fastapi import APIRouter, HTTPException


@dataclass
class CdemoGeneralInfo:
    """Data structure from COBOL group CDEMO-GENERAL-INFO."""
    cdemo_from_tranid: str = field(default='', metadata={'pic': 'X(04)', 'max_length': 4})
    cdemo_from_program: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    cdemo_to_tranid: str = field(default='', metadata={'pic': 'X(04)', 'max_length': 4})
    cdemo_to_program: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    cdemo_user_id: str = field(default='', metadata={'pic': 'X(08)', 'max_length': 8})
    CDEMO_USRTYP_ADMIN: ClassVar[str] = 'A'
    CDEMO_USRTYP_USER: ClassVar[str] = 'U'
    cdemo_user_type: str = field(default='', metadata={'pic': 'X(01)', 'max_length': 1})
    CDEMO_PGM_ENTER: ClassVar[str] = '0'
    CDEMO_PGM_REENTER: ClassVar[str] = '1'
    cdemo_pgm_context: int = field(default=0, metadata={'pic': '9(01)', 'max_digits': 1})


@dataclass
class CdemoCustomerInfo:
    """Data structure from COBOL group CDEMO-CUSTOMER-INFO."""
    cdemo_cust_id: int = field(default=0, metadata={'pic': '9(09)', 'max_digits': 9})
    cdemo_cust_fname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    cdemo_cust_mname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    cdemo_cust_lname: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})


@dataclass
class CdemoAccountInfo:
    """Data structure from COBOL group CDEMO-ACCOUNT-INFO."""
    cdemo_acct_id: int = field(default=0, metadata={'pic': '9(11)', 'max_digits': 11})
    cdemo_acct_status: str = field(default='', metadata={'pic': 'X(01)', 'max_length': 1})


@dataclass
class CdemoCardInfo:
    """Data structure from COBOL group CDEMO-CARD-INFO."""
    cdemo_card_num: int = field(default=0, metadata={'pic': '9(16)', 'max_digits': 16})


@dataclass
class CdemoMoreInfo:
    """Data structure from COBOL group CDEMO-MORE-INFO."""
    cdemo_last_map: str = field(default='', metadata={'pic': 'X(7)', 'max_length': 7})
    cdemo_last_mapset: str = field(default='', metadata={'pic': 'X(7)', 'max_length': 7})


@dataclass
class CarddemoCommarea:
    """Data structure from COBOL copybook COCOM01Y."""
    cdemo_general_info: CdemoGeneralInfo = field(default_factory=CdemoGeneralInfo)
    cdemo_customer_info: CdemoCustomerInfo = field(default_factory=CdemoCustomerInfo)
    cdemo_account_info: CdemoAccountInfo = field(default_factory=CdemoAccountInfo)
    cdemo_card_info: CdemoCardInfo = field(default_factory=CdemoCardInfo)
    cdemo_more_info: CdemoMoreInfo = field(default_factory=CdemoMoreInfo)

Cocom01y = CarddemoCommarea


@dataclass
class Cotrn1ai:
    """Data structure from COBOL copybook COTRN01."""
    trnnamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnnamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamei: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    title01l: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    title01f: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01i: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curdatel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    curdatef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    pgmnamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    pgmnamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    title02l: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    title02f: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02i: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curtimel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    curtimef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimei: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    trnidinl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnidinf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidini: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    trnidl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnidf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidi: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    cardnuml: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    cardnumf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumi: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    ttypcdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    ttypcdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    ttypcdi: str = field(default='', metadata={'pic': 'X(2)', 'max_length': 2})
    tcatcdl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    tcatcdf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tcatcdi: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    trnsrcl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnsrcf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnsrci: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tdescl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    tdescf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tdesci: str = field(default='', metadata={'pic': 'X(60)', 'max_length': 60})
    trnamtl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    trnamtf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnamti: str = field(default='', metadata={'pic': 'X(12)', 'max_length': 12})
    torigdtl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    torigdtf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    torigdti: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tprocdtl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    tprocdtf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tprocdti: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    midl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    midf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    midi: str = field(default='', metadata={'pic': 'X(9)', 'max_length': 9})
    mnamel: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mnamef: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mnamei: str = field(default='', metadata={'pic': 'X(30)', 'max_length': 30})
    mcityl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mcityf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcityi: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    mzipl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    mzipf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mzipi: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    errmsgl: int = field(default=0, metadata={'pic': 'S9(4)', 'max_digits': 4, 'signed': True, 'usage': 'COMP'})
    errmsgf: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgi: str = field(default='', metadata={'pic': 'X(78)', 'max_length': 78})
    trnnamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnnameo: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    title01c: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01p: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01h: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01v: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title01o: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curdatec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdateh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdatev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curdateo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    pgmnamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    pgmnameo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    title02c: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02p: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02h: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02v: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    title02o: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    curtimec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimeh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    curtimeo: str = field(default='', metadata={'pic': 'X(8)', 'max_length': 8})
    trnidinc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidinp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidinh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidinv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidino: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    trnidc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnidv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnido: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    cardnumc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnump: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    cardnumo: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    ttypcdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    ttypcdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    ttypcdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    ttypcdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    ttypcdo: str = field(default='', metadata={'pic': 'X(2)', 'max_length': 2})
    tcatcdc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tcatcdp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tcatcdh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tcatcdv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tcatcdo: str = field(default='', metadata={'pic': 'X(4)', 'max_length': 4})
    trnsrcc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnsrcp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnsrch: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnsrcv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnsrco: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tdescc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tdescp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tdesch: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tdescv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tdesco: str = field(default='', metadata={'pic': 'X(60)', 'max_length': 60})
    trnamtc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnamtp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnamth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnamtv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    trnamto: str = field(default='', metadata={'pic': 'X(12)', 'max_length': 12})
    torigdtc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    torigdtp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    torigdth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    torigdtv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    torigdto: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tprocdtc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tprocdtp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tprocdth: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tprocdtv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    tprocdto: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    midc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    midp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    midh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    midv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mido: str = field(default='', metadata={'pic': 'X(9)', 'max_length': 9})
    mnamec: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mnamep: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mnameh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mnamev: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mnameo: str = field(default='', metadata={'pic': 'X(30)', 'max_length': 30})
    mcityc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcityp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcityh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcityv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mcityo: str = field(default='', metadata={'pic': 'X(25)', 'max_length': 25})
    mzipc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mzipp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mziph: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mzipv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    mzipo: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    errmsgc: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgp: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgh: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgv: str = field(default='', metadata={'pic': 'X', 'max_length': 1})
    errmsgo: str = field(default='', metadata={'pic': 'X(78)', 'max_length': 78})

Cotrn01 = Cotrn1ai


@dataclass
class CcdaScreenTitle:
    """Data structure from COBOL copybook COTTL01Y."""
    ccda_title01: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    ccda_title02: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})
    ccda_thank_you: str = field(default='', metadata={'pic': 'X(40)', 'max_length': 40})

Cottl01y = CcdaScreenTitle


@dataclass
class WsCurdate:
    """Data structure from COBOL group WS-CURDATE."""
    ws_curdate_year: int = field(default=0, metadata={'pic': '9(04)', 'max_digits': 4})
    ws_curdate_month: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_day: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurtime:
    """Data structure from COBOL group WS-CURTIME."""
    ws_curtime_hours: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_minute: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_second: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_milsec: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurdateData:
    """Data structure from COBOL group WS-CURDATE-DATA."""
    ws_curdate: WsCurdate = field(default_factory=WsCurdate)
    ws_curdate_n: Optional[int] = field(default=None, metadata={'pic': '9(08)', 'max_digits': 8})  # REDEFINES WS-CURDATE
    ws_curtime: WsCurtime = field(default_factory=WsCurtime)
    ws_curtime_n: Optional[int] = field(default=None, metadata={'pic': '9(08)', 'max_digits': 8})  # REDEFINES WS-CURTIME


@dataclass
class WsCurdateMmDdYy:
    """Data structure from COBOL group WS-CURDATE-MM-DD-YY."""
    ws_curdate_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_dd: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curdate_yy: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsCurtimeHhMmSs:
    """Data structure from COBOL group WS-CURTIME-HH-MM-SS."""
    ws_curtime_hh: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_curtime_ss: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})


@dataclass
class WsTimestamp:
    """Data structure from COBOL group WS-TIMESTAMP."""
    ws_timestamp_dt_yyyy: int = field(default=0, metadata={'pic': '9(04)', 'max_digits': 4})
    ws_timestamp_dt_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_dt_dd: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_hh: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_mm: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_ss: int = field(default=0, metadata={'pic': '9(02)', 'max_digits': 2})
    ws_timestamp_tm_ms6: int = field(default=0, metadata={'pic': '9(06)', 'max_digits': 6})


@dataclass
class WsDateTime:
    """Data structure from COBOL copybook CSDAT01Y."""
    ws_curdate_data: WsCurdateData = field(default_factory=WsCurdateData)
    ws_curdate_mm_dd_yy: WsCurdateMmDdYy = field(default_factory=WsCurdateMmDdYy)
    ws_curtime_hh_mm_ss: WsCurtimeHhMmSs = field(default_factory=WsCurtimeHhMmSs)
    ws_timestamp: WsTimestamp = field(default_factory=WsTimestamp)

Csdat01y = WsDateTime


@dataclass
class CcdaCommonMessages:
    """Data structure from COBOL copybook CSMSG01Y."""
    ccda_msg_thank_you: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})
    ccda_msg_invalid_key: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})

Csmsg01y = CcdaCommonMessages


@dataclass
class TranRecord:
    """Data structure from COBOL copybook CVTRA05Y."""
    tran_id: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    tran_type_cd: str = field(default='', metadata={'pic': 'X(02)', 'max_length': 2})
    tran_cat_cd: int = field(default=0, metadata={'pic': '9(04)', 'max_digits': 4})
    tran_source: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tran_desc: str = field(default='', metadata={'pic': 'X(100)', 'max_length': 100})
    tran_amt: Decimal = field(default=Decimal('0'), metadata={'pic': 'S9(09)V99', 'max_digits': 9, 'scale': 2, 'signed': True})
    tran_merchant_id: int = field(default=0, metadata={'pic': '9(09)', 'max_digits': 9})
    tran_merchant_name: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})
    tran_merchant_city: str = field(default='', metadata={'pic': 'X(50)', 'max_length': 50})
    tran_merchant_zip: str = field(default='', metadata={'pic': 'X(10)', 'max_length': 10})
    tran_card_num: str = field(default='', metadata={'pic': 'X(16)', 'max_length': 16})
    tran_orig_ts: str = field(default='', metadata={'pic': 'X(26)', 'max_length': 26})
    tran_proc_ts: str = field(default='', metadata={'pic': 'X(26)', 'max_length': 26})

Cvtra05y = TranRecord


@dataclass
class Dfhaid:
    """Data structure from COBOL copybook DFHAID.
    
    TODO: Map fields from copybook definition.
    """
    pass


@dataclass
class Dfhbmsca:
    """Data structure from COBOL copybook DFHBMSCA.
    
    TODO: Map fields from copybook definition.
    """
    pass


class Cotrn01c:
    """
    Modern equivalent of COBOL program COTRN01C.
    
    Calls: CDEMO-TO-PROGRAM
    Files: COTRN1A (CICS_IO), COTRN1A (CICS_IO), WS-TRANSACT-FILE (CICS_IO)
    """

    def __init__(self):
        self.cocom01y = Cocom01y()
        self.cotrn01 = Cotrn01()
        self.cottl01y = Cottl01y()
        self.csdat01y = Csdat01y()
        self.csmsg01y = Csmsg01y()
        self.cvtra05y = Cvtra05y()
        self.dfhaid = Dfhaid()
        self.dfhbmsca = Dfhbmsca()

    def main_para(self) -> None:
        """
        COBOL PERFORMs: , , , , 
        CICS: RETURN()
        Writes: CARDDEMO-COMMAREA, CCDA-MSG-INVALID-KEY, CDEMO-CT01-TRN-SELECTED, CDEMO-FROM-PROGRAM, CDEMO-PGM-REENTER
        """
        # CICS RETURN()

    def process_enter_key(self) -> None:
        """
        COBOL PERFORMs: , , 
        Writes: CARDNUMI, COTRN1AI, MCITYI, MIDI, MNAMEI
        """

    def return_to_prev_screen(self) -> None:
        """
        COBOL CALLs: 
        CICS: XCTL()
        Writes: CARDDEMO-COMMAREA, CDEMO-FROM-PROGRAM, CDEMO-FROM-TRANID, CDEMO-PGM-CONTEXT, CDEMO-TO-PROGRAM
        """
        # CICS XCTL()
        # TODO: Replace with service call

    def send_trnview_screen(self) -> None:
        """
        COBOL PERFORMs: 
        CICS: SEND()
        Writes: CICS, COTRN01, COTRN1A, COTRN1AO, CURSOR
        """
        # CICS SEND()
        # TODO: Replace with API endpoint handler

    def receive_trnview_screen(self) -> None:
        """
        CICS: RECEIVE()
        """
        # CICS RECEIVE()
        # TODO: Replace with API endpoint handler

    def populate_header_info(self) -> None:
        """
        Writes: CCDA-TITLE01, CCDA-TITLE02, COTRN1AO, CURDATEO, CURTIMEO
        """
        raise NotImplementedError

    def read_transact_file(self) -> None:
        """
        COBOL PERFORMs: 
        CICS: READ(WS-TRANSACT-FILE)
        """
        # CICS READ(WS-TRANSACT-FILE)
        # TODO: Replace with database operation

    def clear_current_screen(self) -> None:
        """
        COBOL PERFORMs: , 
        """

    def initialize_all_fields(self) -> None:
        raise NotImplementedError

    def run(self) -> None:
        """Main entry point — mirrors PROCEDURE DIVISION."""
        self.main_para()
        self.process_enter_key()
        self.return_to_prev_screen()


if __name__ == "__main__":
    program = Cotrn01c()
    program.run()
